# Atividade tf-idf

* https://towardsdatascience.com/tf-idf-explained-and-python-sklearn-implementation-b020c5e83275
* https://medium.com/geekculture/text-feature-extraction-2-3-tf-idf-model-c3a8f7a92bc9

In [62]:
import pandas as pd
import nltk
import re
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer

In [5]:

dataset = [
    "I enjoy reading about Machine Learning and Machine Learning is my PhD subject",
    "I would enjoy a walk in the park",
    "I was reading in the library"
]

In [12]:
dataset

['I enjoy reading about Machine Learning and Machine Learning is my PhD subject',
 'I would enjoy a walk in the park',
 'I was reading in the library']

In [6]:
tfIdfVectorizer=TfidfVectorizer(use_idf=True)
tfIdf = tfIdfVectorizer.fit_transform(dataset)
df = pd.DataFrame(tfIdf[0].T.todense(), index=tfIdfVectorizer.get_feature_names(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)
print (df.head(25))

            TF-IDF
machine   0.513720
learning  0.513720
about     0.256860
subject   0.256860
phd       0.256860
and       0.256860
my        0.256860
is        0.256860
reading   0.195349
enjoy     0.195349
library   0.000000
park      0.000000
in        0.000000
the       0.000000
walk      0.000000
was       0.000000
would     0.000000


## Vamos aplicar a um dataset 

In [66]:
df = pd.read_csv('BBC_News_Train.csv')
df.shape

(1490, 3)

In [67]:
df.head()

ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [68]:
#stopword removal and lemmatization
stopwords = nltk.corpus.stopwords.words('english')
lemmatizer = WordNetLemmatizer()

In [69]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/walkiria/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Split in train and text

In [70]:
X = df['Text']
y = df['Category']

In [71]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

# Pre-processamento 

In [72]:
train_X=[]
test_X=[]

In [35]:
#text pre processing
for i in range(0, len(X_train)):
    review = re.sub('[^a-zA-Z]', ' ', X_train[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
    review = ' '.join(review)
    train_X.append(review)

KeyError: 10

In [73]:
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)

In [74]:
#text pre processing
for i in range(0, len(X_train)):
    review = re.sub('[^a-zA-Z]', ' ', X_train[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
    review = ' '.join(review)
    train_X.append(review)

In [75]:
#text pre processing
for i in range(0, len(X_test)):
    review = re.sub('[^a-zA-Z]', ' ', X_test[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
    review = ' '.join(review)
    test_X.append(review)

# TFIDF

In [76]:
tfIdfVectorizer=TfidfVectorizer(use_idf=True)
#applying to training 
tfIdf = tfIdfVectorizer.fit_transform(train_X)

X_train_tf = tfIdfVectorizer.transform(train_X)


In [77]:
print("n_samples: %d, n_features: %d" % tfIdf.shape)

n_samples: 998, n_features: 17559


In [90]:
X_train_tf

<1x17559 sparse matrix of type '<class 'numpy.float64'>'
	with 160 stored elements in Compressed Sparse Row format>

In [93]:
pd.DataFrame(X_train_tf.toarray())

0      1      2      3      4      5      6      7      8      9      \
0      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
993    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
994    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
995    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
996    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
997    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

     ...  17549  17550  17551  17552  17553  17554  17555     17556  17557  \
0    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
1    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.045234    0.0   
2    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
3    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
4    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
..   ...    ...    ...    ...    ...    ...    ...    ...       ...    ...   
993  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
994  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
995  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
996  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
997  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   

     17558  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
..     ...  
993    0.0  
994    0.0  
995    0.0  
996    0.0  
997    0.0  

[998 rows x 17559 columns]

In [92]:
X_train_tf_df = pd.DataFrame(X_train_tf[0].T.todense(), index=tfIdfVectorizer.get_feature_names(), columns=["TF-IDF"])
X_train_tf_df = X_train_tf_df.sort_values('TF-IDF', ascending=False)
print (X_train_tf_df.head(25))

                 TF-IDF
music          0.477173
copyright      0.270245
school         0.221208
lesson         0.207918
piracy         0.204381
industry       0.177928
songwriter     0.170152
pupil          0.155938
creatives      0.133814
bmr            0.133814
scheme         0.125369
education      0.121886
silva          0.116817
secondary      0.108098
chamber        0.105913
child          0.104724
composer       0.103959
young          0.102193
career         0.101009
learning       0.097717
cd             0.096437
understanding  0.096437
important      0.094492
pack           0.088508
issue          0.083933


In [52]:
# print(tfIdfVectorizer.vocabulary_)

In [78]:
df_tfidf = pd.DataFrame(tfIdf[0].T.todense(), index=tfIdfVectorizer.get_feature_names(), columns=["TF-IDF"])
df_tfidf = df_tfidf.sort_values('TF-IDF', ascending=False)

In [79]:
df_tfidf

TF-IDF
music      0.477173
copyright  0.270245
school     0.221208
lesson     0.207918
piracy     0.204381
...             ...
findlay    0.000000
fine       0.000000
fined      0.000000
finegold   0.000000
zvonareva  0.000000

[17559 rows x 1 columns]

In [80]:
#transforming test data into tf-idf matrix
X_test_tf = tfIdfVectorizer.transform(test_X)

In [81]:
print("n_samples: %d, n_features: %d" % X_test_tf.shape)

n_samples: 492, n_features: 17559


## Classificador

In [82]:
#naive bayes classifier
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf, y_train)

MultinomialNB()

In [83]:
#predicted y
y_pred = naive_bayes_classifier.predict(X_test_tf)

In [85]:
df['Category'].unique()

array(['business', 'tech', 'politics', 'sport', 'entertainment'],
      dtype=object)

In [86]:
print(metrics.classification_report(y_test, y_pred, target_names=['business', 'tech', 'politics', 'sport', 'entertainment']))


               precision    recall  f1-score   support

     business       0.97      0.97      0.97       117
         tech       1.00      0.95      0.98        88
     politics       0.95      0.95      0.95        93
        sport       0.96      1.00      0.98       110
entertainment       0.95      0.94      0.95        84

     accuracy                           0.97       492
    macro avg       0.97      0.96      0.96       492
 weighted avg       0.97      0.97      0.97       492



In [88]:
print("Confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

Confusion matrix:
[[114   0   1   0   2]
 [  1  84   1   2   0]
 [  2   0  88   1   2]
 [  0   0   0 110   0]
 [  1   0   3   1  79]]
